KaratePortal/KaratePortal/Controllers/ArtController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KaratePortal.Controllers
{
    public class ArtController : Controller
    {
    
        public ActionResult ShowArts()
        {
            return View();
        }
    }
}

KaratePortal/KaratePortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - KaratePortal</title>
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="color:red">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Martial art", "ShowArts", "Art", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav nav-pills" style="position:relative; margin-top:7px">
                    <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Team", "ShowStudentTeam", "Team")</li>
                    <li class="dropdown" style="color:aquamarine">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Persons <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Coaches", "ShowCoaches", "Coach")</li>
                            <li>@Html.ActionLink("Students", "ShowStudents", "Student")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>